version: '3'
services:
  mein-mongodb-kunde:
    image: mongo:latest
    container_name: mein-docker-kunde
    ports:
      - "27018:27017"
    networks:
      - meine-netzwerk-kunde

  microservice2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mein-mongodb-kunde
    networks:
      - meine-netzwerk-kunde

networks:
  meine-netzwerk-kunde:
