version: '3'
services:
  mein-mongodb-user:
    image: mongo:latest
    container_name: mein-docker-user
    ports:
      - "27018:27018"
    networks:
      - meine-netzwerk-user

  microservice2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mein-mongodb-user
    networks:
      - meine-netzwerk-user

networks:
  meine-netzwerk-user:
